kind: pipeline
name: build-and-test

steps:
- name: test
  image: rust:1.47
  commands:
  - apt-get update
  - apt-get install -y cmake
  - cargo build --verbose --all
  - cargo test --verbose --all

- name: docker
  image: plugins/docker
  when:
    branch:
    - master
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: projectmoon/chronicle-dicebot
    registry: gchr.io
