[package]
name = "chronicle-dicebot"
version = "0.2.0"
authors = ["Taylor C. Richberger <taywee@gmx.com>", "projectmoon <projectmoon@agnos.is>"]
edition = "2018"
license = 'MIT'
description = 'A simple async Matrix dicebot'
readme = 'README.md'
repository = 'https://github.com/ProjectMoon/matrix-dicebot'
keywords = ["games", "dice", "matrix", "bot"]
categories = ["games"]

[dependencies]
reqwest = "0.10"
serde_json = "1"
toml = "0.5"
nom = "5"
rand = "0.7"
thiserror = "1.0"
itertools = "0.9"

[dependencies.serde]
version = "1"
features = ['derive']

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "macros", "time", "signal"]
