[package]
name = "axfive-matrix-dicebot"
version = "0.1.0"
authors = ["Taylor C. Richberger <taywee@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
serde_json = "1"
toml = "0.5"
nom = "5"

[dependencies.serde]
version = "1"
features = ['derive']

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "macros", "time", "signal"]
