[package]
name = "chronicle-dicebot"
version = "0.4.0"
authors = ["Taylor C. Richberger <taywee@gmx.com>", "projectmoon <projectmoon@agnos.is>"]
edition = "2018"
license = 'MIT'
description = 'A simple async Matrix dicebot'
readme = 'README.md'
repository = 'https://github.com/ProjectMoon/matrix-dicebot'
keywords = ["games", "dice", "matrix", "bot"]
categories = ["games"]

[dependencies]
log = "0.4"
env_logger = "0.7"
toml = "0.5"
nom = "5"
rand = "0.7"
thiserror = "1.0"
itertools = "0.9"
async-trait = "0.1"
url = "2.1"
dirs = "3.0"

# The versioning of the matrix SDK follows its Cargo.toml. The SDK and
# macros are on master, but it imports the common and base from 0.1.0.
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "master" }
matrix-sdk-common-macros = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "master" }
matrix-sdk-common = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "0.1.0" }
matrix-sdk-base = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "0.1.0", default_features = false }

[dependencies.serde]
version = "1"
features = ['derive']

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "macros", "time", "signal"]
