[package]
name = "chronicle-dicebot"
version = "0.7.0"
authors = ["Taylor C. Richberger <taywee@gmx.com>", "projectmoon <projectmoon@agnos.is>"]
edition = "2018"
license = 'MIT'
description = 'A simple async Matrix dicebot'
readme = 'README.md'
repository = 'https://github.com/ProjectMoon/matrix-dicebot'
keywords = ["games", "dice", "matrix", "bot"]
categories = ["games"]

[dependencies]
log = "0.4"
env_logger = "0.7"
toml = "0.5"
nom = "5"
rand = "0.7"
thiserror = "1.0"
itertools = "0.9"
async-trait = "0.1"
url = "2.1"
dirs = "3.0"
indoc = "1.0"
combine = "4.3"
sled = "0.34"
zerocopy = "0.3"
byteorder = "1.3"
futures = "0.3"
phf = { version = "0.7", features = ["macros"] }
olm-sys = "1.0"
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk", rev = "master" }

[dependencies.serde]
version = "1"
features = ['derive']

[dependencies.tokio]
version = "0.2"
features = [ "full" ]

[dev-dependencies]
tempfile = "3.1"
