[package]
name = "tenebrous-rpc"
version = "0.1.0"
authors = ["projectmoon <projectmoon@agnos.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic", branch = "master" }

[dependencies]
tonic = { git = "https://github.com/hyperium/tonic", branch = "master" }
prost = "0.7"