[package]
name = "tenebrous-api"
version = "0.1.0"
authors = ["projectmoon <projectmoon@agnos.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { git = "https://github.com/hyperium/tonic", branch = "master" }
tonic-web = { git = "https://github.com/hyperium/tonic", branch = "master" }
prost = "0.7"
tenebrous-rpc = { path = "../rpc" }
tokio-stream = { version = "0.1", features = ["net"] }

[dependencies.tokio]
version = "1"
features = [ "full" ]
